# Generated by Django 3.1 on 2020-08-27 04:54

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='cadastro_pf',
            field=cpf_field.models.CPFField(default=1, max_length=14, verbose_name='cadastro_pf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
