# Generated by Django 3.1 on 2020-08-28 05:57

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200827_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='cadastro_pf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
