# Generated by Django 3.1 on 2020-09-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200828_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='cadastro_pf',
        ),
    ]
