# Generated by Django 3.1.1 on 2021-01-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profileuser_cadastro_pf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='data_nascimento',
        ),
    ]
