# Generated by Django 3.1.1 on 2021-03-16 20:04

import cpf_field.models
from django.db import migrations, models
import django.utils.timezone
import requests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoEducacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastro_pf', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=15, validators=[requests.models.only_int])),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('escola', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoIluminacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_luz', models.FileField(upload_to='arquivos/')),
                ('rg', models.CharField(max_length=15, validators=[requests.models.only_int])),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMeioAmbiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoTransito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Defeito No Semáforo', 'Defeito no Semáforo'), ('Estacionamento Irregular', 'Estacionamento Irregular'), ('Sinalização Irregular', 'Sinalização Irregular')], max_length=100)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('comentario', models.TextField(blank=True, default='')),
            ],
        ),
    ]
