# Generated by Django 3.1 on 2020-09-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='imagem',
            field=models.ImageField(upload_to='imagens/'),
        ),
    ]
