# Generated by Django 3.1 on 2020-09-09 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20200904_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atual', models.CharField(choices=[('Recebido', 'Recebido'), ('Em andamento', 'Em andamento'), ('Recusado', 'Recusado'), ('Concluído', 'Concluído')], default='Recebido', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('Acidente', 'Acidente'), ('Defeito No Semáforo', 'Defeito no Semáforo'), ('Estacionamento Irregular', 'Estacionamento Irregular'), ('Sinalização Irregular', 'Sinalização Irregular')], max_length=100),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='requests.status'),
        ),
    ]
