# Generated by Django 3.1 on 2020-09-09 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20200908_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(choices=[('Água Verde', 'Água Verde'), ('Alto Frigorífico', 'Alto Frigorífico'), ('Alto da Tijuca', 'Alto da Tijuca'), ('Alto das Palmeiras', 'Alto das Palmeiras'), ('Boa Vista', 'Boa Vista'), ("Campo d'Água Verde", "Campo d'Água Verde"), ('Centro', 'Centro'), ('Jardim Esperança', 'Jardim Esperança'), ('Piedade', 'Piedade'), ('Sossego', 'Sossego')], max_length=200)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('referencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='atual',
            field=models.CharField(choices=[('Recebido', 'Recebido'), ('Em andamento', 'Em andamento'), ('Recusado', 'Recusado'), ('Concluído', 'Concluído')], max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.endereco'),
        ),
    ]
