# Generated by Django 3.1 on 2020-09-27 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0005_auto_20200909_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoEducacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoTransito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Defeito No Semáforo', 'Defeito no Semáforo'), ('Estacionamento Irregular', 'Estacionamento Irregular'), ('Sinalização Irregular', 'Sinalização Irregular')], max_length=100)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Solicitacao',
        ),
        migrations.AddField(
            model_name='solicitacaotransito',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.endereco'),
        ),
        migrations.AddField(
            model_name='solicitacaotransito',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaotransito',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='requests.status'),
        ),
    ]
