# Generated by Django 3.1 on 2020-09-27 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0007_auto_20200927_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoIluminacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_luz', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=15)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField()),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
