# Generated by Django 3.1 on 2020-09-28 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0008_solicitacaoiluminacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoUPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(max_length=15)),
                ('card_sus', models.CharField(max_length=20)),
                ('comprovante_residencia', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
