# Generated by Django 3.1.1 on 2020-09-30 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_solicitacaoupa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaotransito',
            name='status',
        ),
        migrations.AlterField(
            model_name='solicitacaoeducacao',
            name='comentario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='solicitacaoiluminacao',
            name='comentario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='solicitacaoiluminacao',
            name='conta_luz',
            field=models.FileField(upload_to='arquivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='solicitacaotransito',
            name='comentario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='solicitacaotransito',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='solicitacaoupa',
            name='comprovante_residencia',
            field=models.FileField(upload_to='arquivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
