# Generated by Django 3.1.1 on 2020-09-30 07:09

from django.db import migrations, models
import requests.models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_auto_20200930_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoeducacao',
            name='rg',
            field=models.CharField(max_length=15, validators=[requests.models.only_int]),
        ),
        migrations.AlterField(
            model_name='solicitacaoiluminacao',
            name='conta_luz',
            field=models.FileField(upload_to='arquivos/'),
        ),
        migrations.AlterField(
            model_name='solicitacaoiluminacao',
            name='rg',
            field=models.CharField(max_length=15, validators=[requests.models.only_int]),
        ),
        migrations.AlterField(
            model_name='solicitacaoupa',
            name='card_sus',
            field=models.CharField(max_length=20, validators=[requests.models.only_int]),
        ),
        migrations.AlterField(
            model_name='solicitacaoupa',
            name='comprovante_residencia',
            field=models.FileField(upload_to='arquivos/'),
        ),
        migrations.AlterField(
            model_name='solicitacaoupa',
            name='rg',
            field=models.CharField(max_length=15, validators=[requests.models.only_int]),
        ),
    ]
