# Generated by Django 3.1.1 on 2021-03-11 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0011_auto_20200930_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMeioAmbiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.endereco')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SolicitacaoUPA',
        ),
    ]
