# Generated by Django 3.1.1 on 2021-03-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceberEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.TextField(max_length=100)),
                ('resposta', models.TextField(max_length=100)),
                ('data_resposta', models.CharField(max_length=100)),
            ],
        ),
    ]
