# Generated by Django 3.1.1 on 2021-03-16 20:04

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviarEmailEducacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.EmailField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('cadastro_pf', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=15)),
                ('escola', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnviarEmailIluminacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.EmailField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=15)),
                ('conta_luz', models.FileField(upload_to='arquivos/')),
            ],
        ),
        migrations.CreateModel(
            name='EnviarEmailTransito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.EmailField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='EnviarEmailMeioAmbiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.EmailField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.endereco')),
            ],
        ),
    ]
