# Generated by Django 3.1.1 on 2020-09-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviaremailtransito',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enviaremailtransito',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
