# Generated by Django 3.1.1 on 2020-09-30 07:09

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendforms', '0002_auto_20200930_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviarEmailEducacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cadastro_pf', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EnviarEmailIluminacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EnviarEmailUPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('rg', models.CharField(max_length=15)),
                ('card_sus', models.CharField(max_length=20)),
            ],
        ),
    ]
