# Generated by Django 3.1.1 on 2021-02-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendforms', '0003_enviaremaileducacao_enviaremaililuminacao_enviaremailupa'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviaremailtransito',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/'),
        ),
    ]
