# Generated by Django 3.1.1 on 2021-03-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendforms', '0004_enviaremailtransito_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviaremaililuminacao',
            name='conta_luz',
            field=models.FileField(default='batata', upload_to='arquivos/'),
            preserve_default=False,
        ),
    ]
