# Generated by Django 3.1.1 on 2021-03-11 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_auto_20210311_0056'),
        ('sendforms', '0005_enviaremaililuminacao_conta_luz'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviarEmailMeioAmbiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.endereco')),
            ],
        ),
        migrations.DeleteModel(
            name='EnviarEmailUPA',
        ),
    ]
