# Generated by Django 3.1.1 on 2021-03-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendforms', '0006_auto_20210311_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviaremailmeioambiente',
            name='email',
            field=models.EmailField(default='JhonyPereiradoVale@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
